name: PHP Security Check

on: [push, pull_request]

jobs:
  security:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Composer Audit
        run: composer audit --format plain

      - name: Run Symfony Security Check
        run: |
          composer require --dev symfony/security-checker
          vendor/bin/security-checker security:check
