name: PHP Syntax Check Pipeline

on: [push, pull_request]

jobs:

  build:
    name: build  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' 

      - name: Syntax check for PHP files
        run: |
          find . -name "*.php" -exec php -l {} \;

  test:
    name: test  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run basic PHP script check
        run: |
          echo "<?php echo 'Test passed!'; ?>" | php
